name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd frontend
          npm install
          # Install missing Babel plugin
          npm install --save-dev @babel/plugin-proposal-private-property-in-object
          # Update Browserslist database
          npx update-browserslist-db@latest

      - name: Build frontend
        run: |
          cd frontend
          # Disable CI mode to prevent treating warnings as errors
          CI='' npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/build
